dateModified: 1549388509
email:
  fromEmail: $EMAIL_FROM_ADDRESS
  fromName: $EMAIL_FROM_NAME
  template: null
  transportSettings:
    encryptionMethod: ssl
    host: $EMAIL_HOST_NAME
    password: $EMAIL_HOST_PASSWORD
    port: '465'
    timeout: '10'
    useAuthentication: '1'
    username: $EMAIL_HOST_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fieldGroups:
  1a4759d6-7c57-4fc3-86d1-ce3c62ed948b:
    name: 'Social Media'
  27aea6ee-8df1-4c97-8fe9-c956a049eb03:
    name: Assets
  3fbdb43a-29d7-4c3e-b657-7031ab65ccb4:
    name: Contact
  74a9b2c3-f924-4c3a-9e27-f2c45b24f1d9:
    name: Legals
  9ace1fad-7441-439d-9f5f-40620d68b63c:
    name: Common
fields:
  0008c3e1-4c0f-4701-b80e-bfcb74b38674:
    contentColumnType: text
    fieldGroup: 1a4759d6-7c57-4fc3-86d1-ce3c62ed948b
    handle: twitterHandle
    instructions: 'Twitter username for the website - without the preceding @. '
    name: 'Twitter Handle'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: handle
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  0efcb020-757f-48f5-a3ad-c5db918a5079:
    contentColumnType: string
    fieldGroup: 3fbdb43a-29d7-4c3e-b657-7031ab65ccb4
    handle: email
    instructions: ''
    name: Email
    searchable: true
    settings:
      placeholder: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Email
  1daffcc0-78ad-4066-934f-57421e0bd5ef:
    contentColumnType: text
    fieldGroup: 27aea6ee-8df1-4c97-8fe9-c956a049eb03
    handle: alt
    instructions: "Alt text (alternative text) is a word or phrase that can be inserted as an attribute to tell Web site viewers the nature or contents of an image. The alt text appears in the code and is good for SEO, Accessibility and is a best practice to include this field. If no Alt Text is specified then the title of the image will be used instead. In some instances Alt text will be autogenerated, an example being Logo assets. \r\n\r\nAlt text should ideally describe the image but would benefit from any keywords. E.g BIM scan of Westminster Hall"
    name: Alt
    searchable: true
    settings:
      charLimit: ''
      code: false
      columnType: text
      initialRows: 4
      multiline: 1
      placeholder: 'Please enter an image description | e.g BIM scan of Westminster Hall'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1faa1946-3247-4cb5-be13-18257f85d5a3:
    contentColumnType: text
    fieldGroup: 1a4759d6-7c57-4fc3-86d1-ce3c62ed948b
    handle: linkedinCompanyName
    instructions: 'To find or update your LinkedIn Company Name please see [this LinkedIn help article](https://www.linkedin.com/help/linkedin/answer/62467/updating-the-url-of-your-company-page?lang=en)'
    name: 'Linkedin Company Name'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: username
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2c286930-21e6-47b4-940e-071e1c977fed:
    contentColumnType: text
    fieldGroup: 74a9b2c3-f924-4c3a-9e27-f2c45b24f1d9
    handle: fullCompanyName
    instructions: 'Please enter the full company name as registered with companies house or the full trading name of the business. '
    name: 'Full Company Name'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2d81e303-5711-4abe-bad0-d7bb9cb25068:
    contentColumnType: text
    fieldGroup: 27aea6ee-8df1-4c97-8fe9-c956a049eb03
    handle: stockSoruceUrl
    instructions: 'Use this field to paste the URL for the original stock/source image. This could be useful to reference Stock images.'
    name: 'Stock/Source Url'
    searchable: true
    settings:
      charLimit: ''
      code: false
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4205fd33-eccc-4ede-90f4-4e26f1e2e1dc:
    contentColumnType: text
    fieldGroup: 9ace1fad-7441-439d-9f5f-40620d68b63c
    handle: teaserCopy
    instructions: "The teaser copy, sometimes referred to as the excerpt,  is used for article/page summaries. This is typically used in listing pages and related link modules.  \r\nThese are sometimes used as META description fallbacks.  There is a restriction of 256 characters to comply with SEO and design rules in the website.  "
    name: 'Teaser Copy'
    searchable: true
    settings:
      charLimit: '256'
      code: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  443dd37f-c495-4014-b43a-8ed2fc0f85a3:
    contentColumnType: text
    fieldGroup: 74a9b2c3-f924-4c3a-9e27-f2c45b24f1d9
    handle: companyNumber
    instructions: ''
    name: 'Company Number'
    searchable: true
    settings:
      charLimit: 8
      code: ''
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  52e82fa9-0507-4677-9f2b-f34dbc5aeddb:
    contentColumnType: text
    fieldGroup: 27aea6ee-8df1-4c97-8fe9-c956a049eb03
    handle: notes
    instructions: 'Use this field to enter any additional notes regarding the image.'
    name: Notes
    searchable: true
    settings:
      charLimit: ''
      code: false
      columnType: text
      initialRows: 4
      multiline: 1
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  66a6808a-8c39-46ae-a30c-eb8758c059e5:
    contentColumnType: string
    fieldGroup: 9ace1fad-7441-439d-9f5f-40620d68b63c
    handle: terms
    instructions: ''
    name: Terms
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_terms}}'
      localizeBlocks: false
      maxBlocks: null
      minBlocks: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  8cd70478-7e5c-4fc8-8c88-e31391998779:
    contentColumnType: text
    fieldGroup: 9ace1fad-7441-439d-9f5f-40620d68b63c
    handle: copy
    instructions: ''
    name: Copy
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: '1'
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  97bb093c-dee5-44c1-99aa-f0cd77c4d7e0:
    contentColumnType: text
    fieldGroup: 1a4759d6-7c57-4fc3-86d1-ce3c62ed948b
    handle: instagramUsername
    instructions: 'Instagram Username. Usually the part after _www.instgram.com/_. Click on the ''Settings'' tab on your Instagram company/fan page and find your ''Username''.'
    name: 'Instagram Username'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: username
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b300f039-a202-4d80-93cf-cdcafcfbb5d9:
    contentColumnType: string
    fieldGroup: 9ace1fad-7441-439d-9f5f-40620d68b63c
    handle: teaserImage
    instructions: "A teaser image is typically used on listing pages and related content modules. The image is usually representative of the article/page. \r\nThis field is might also be used as a fallback image for SEO meta images. \r\n\r\n**More Information**  \r\n_For more information on SEO Images please visit [Yoast SEO](https://yoast.com/advanced-technical-seo-social-image-ogimage-tags/) and [Open Graph](http://ogp.me/)_"
    name: 'Teaser Image'
    searchable: true
    settings:
      allowedKinds: null
      defaultUploadLocationSource: 'volume:2704582f-5c82-44da-9552-cddd0a262a82'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: 'Add Image'
      singleUploadLocationSource: 'volume:2704582f-5c82-44da-9552-cddd0a262a82'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b798f838-613c-4876-bc1b-df4b7278fc70:
    contentColumnType: text
    fieldGroup: 74a9b2c3-f924-4c3a-9e27-f2c45b24f1d9
    handle: vatNumber
    instructions: ''
    name: 'VAT Number'
    searchable: true
    settings:
      charLimit: 14
      code: ''
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  be0acf2a-68de-4d25-a4a0-dbd1e614ef7a:
    contentColumnType: text
    fieldGroup: 3fbdb43a-29d7-4c3e-b657-7031ab65ccb4
    handle: address
    instructions: ''
    name: Address
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: 5
      multiline: 1
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c8a96201-891a-43e4-89e9-3263caa261e5:
    contentColumnType: text
    fieldGroup: 3fbdb43a-29d7-4c3e-b657-7031ab65ccb4
    handle: telephone
    instructions: ''
    name: Telephone
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d18100aa-55bf-40cf-b1c3-90aaf38e7bdd:
    contentColumnType: text
    fieldGroup: 1a4759d6-7c57-4fc3-86d1-ce3c62ed948b
    handle: youtubeUrl
    instructions: 'The URL for your YouTube channel, account or playlist. To find your YouTube url or to create one please read this [YouTube help article](https://support.google.com/youtube/answer/2657968?hl=en-GB)'
    name: 'YouTube URL'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: handle
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f71b834e-adae-4e0e-95ec-d4736c74cfa2:
    contentColumnType: text
    fieldGroup: 1a4759d6-7c57-4fc3-86d1-ce3c62ed948b
    handle: facebookUsername
    instructions: 'Facebook Username. Click on the ''About'' tab on your Facebook company/fan page, scroll to the Username.'
    name: 'Facebook Username'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: username
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
globalSets:
  25031c1d-296c-4f89-a356-86ccfb0b1c5e:
    fieldLayouts:
      06e266e4-b842-4757-b257-c0bf5c5c1055:
        tabs:
          - fields:
              0008c3e1-4c0f-4701-b80e-bfcb74b38674:
                required: false
                sortOrder: 2
              1faa1946-3247-4cb5-be13-18257f85d5a3:
                required: false
                sortOrder: 4
              97bb093c-dee5-44c1-99aa-f0cd77c4d7e0:
                required: false
                sortOrder: 3
              d18100aa-55bf-40cf-b1c3-90aaf38e7bdd:
                required: false
                sortOrder: 5
              f71b834e-adae-4e0e-95ec-d4736c74cfa2:
                required: false
                sortOrder: 1
            name: 'Scoial Accounts'
            sortOrder: 1
    handle: socialMedia
    name: 'Social Media'
  5a6a5511-e946-4be0-9b5c-c0b840f9f464:
    fieldLayouts:
      05ea6d16-e7ec-461d-92d9-0968b91bcb66:
        tabs:
          - fields:
              0efcb020-757f-48f5-a3ad-c5db918a5079:
                required: true
                sortOrder: 1
              be0acf2a-68de-4d25-a4a0-dbd1e614ef7a:
                required: true
                sortOrder: 3
              c8a96201-891a-43e4-89e9-3263caa261e5:
                required: true
                sortOrder: 2
            name: Contact
            sortOrder: 1
          - fields:
              2c286930-21e6-47b4-940e-071e1c977fed:
                required: false
                sortOrder: 1
              443dd37f-c495-4014-b43a-8ed2fc0f85a3:
                required: false
                sortOrder: 2
              b798f838-613c-4876-bc1b-df4b7278fc70:
                required: false
                sortOrder: 3
            name: Legals
            sortOrder: 2
    handle: companyInformation
    name: 'Company Information'
matrixBlockTypes:
  7cd0b9ad-8198-4647-aa5a-62c7032541d8:
    field: 66a6808a-8c39-46ae-a30c-eb8758c059e5
    fieldLayouts:
      20dc58dd-92c8-4d68-8987-64903452f0ae:
        tabs:
          - fields:
              26f79cf2-503e-4c50-aa72-f671e2b629f2:
                required: true
                sortOrder: 2
              371e5387-fab3-4179-b33f-7c8b97815ecc:
                required: true
                sortOrder: 1
            name: Content
            sortOrder: 1
    fields:
      26f79cf2-503e-4c50-aa72-f671e2b629f2:
        contentColumnType: string
        fieldGroup: null
        handle: terms
        instructions: 'Please don''t include numbers as these will dynamically be created based on the blocks position.'
        name: Terms
        searchable: true
        settings:
          errorMessage: 'Unable to find component class ''craft\fields\RichText''.'
          expectedType: craft\fields\RichText
          settings:
            availableAssetSources: '*'
            availableTransforms: '*'
            cleanupHtml: 1
            columnType: text
            configFile: Standard.json
            purifierConfig: ''
            purifyHtml: 1
        translationKeyFormat: null
        translationMethod: none
        type: craft\fields\MissingField
      371e5387-fab3-4179-b33f-7c8b97815ecc:
        contentColumnType: text
        fieldGroup: null
        handle: heading
        instructions: ''
        name: Heading
        searchable: true
        settings:
          charLimit: ''
          code: false
          columnType: text
          initialRows: 4
          multiline: ''
          placeholder: ''
        translationKeyFormat: null
        translationMethod: none
        type: craft\fields\PlainText
    handle: termsBlock
    name: 'Terms Block'
    sortOrder: 1
plugins:
  field-manager:
    edition: standard
    enabled: true
  image-resizer:
    edition: standard
    enabled: true
  imager:
    edition: standard
    enabled: true
  minify:
    edition: standard
    enabled: true
  redactor:
    edition: standard
    enabled: true
  relabel:
    edition: standard
    enabled: true
  seomatic:
    edition: standard
    enabled: true
  super-table:
    edition: standard
    enabled: true
  typogrify:
    edition: standard
    enabled: true
sections:
  46b46ed4-a0ea-40e9-8ebf-41874babf122:
    enableVersioning: false
    entryTypes:
      aad9c1a9-a657-4829-96ac-3485bf61f374:
        fieldLayouts:
          bfef7f63-3c26-4e33-ac93-8eac679b5547:
            tabs:
              - fields:
                  4205fd33-eccc-4ede-90f4-4e26f1e2e1dc:
                    required: false
                    sortOrder: 2
                  b300f039-a202-4d80-93cf-cdcafcfbb5d9:
                    required: false
                    sortOrder: 1
                name: 'Tab 1'
                sortOrder: 1
        handle: contact
        hasTitleField: false
        name: Contact
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: ''
    handle: contact
    name: Contact
    propagateEntries: true
    siteSettings:
      e9b5ffaf-2fae-43e5-8160-4a0bc36dadd0:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: contact
    type: single
  6bec8522-2f36-4403-9812-127a64f0d9c7:
    enableVersioning: true
    entryTypes:
      90bfc578-faf3-451e-94d7-ce7939b44f4a:
        handle: home
        hasTitleField: false
        name: Home
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: null
    handle: home
    name: Home
    propagateEntries: true
    siteSettings:
      e9b5ffaf-2fae-43e5-8160-4a0bc36dadd0:
        enabledByDefault: true
        hasUrls: true
        template: index.twig
        uriFormat: __home__
    type: single
  761595e6-8de4-4a64-b7a1-6b3b12c0348c:
    enableVersioning: true
    entryTypes:
      26b8df92-c940-4de0-8d1c-15409abaee0a:
        fieldLayouts:
          14c7eed1-9cdb-4620-b3e5-259ac351ce76:
            tabs:
              - fields:
                  66a6808a-8c39-46ae-a30c-eb8758c059e5:
                    required: false
                    sortOrder: 2
                  8cd70478-7e5c-4fc8-8c88-e31391998779:
                    required: false
                    sortOrder: 1
                name: Content
                sortOrder: 1
        handle: terms
        hasTitleField: true
        name: Terms
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: terms
    name: Terms
    propagateEntries: true
    siteSettings:
      e9b5ffaf-2fae-43e5-8160-4a0bc36dadd0:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'terms/{slug}'
    structure:
      maxLevels: '1'
      uid: 111b38c3-19b6-43b7-9a77-ff1db8326f75
    type: structure
siteGroups:
  13a10389-f66f-49d3-bbfe-5a5918ca298f:
    name: default
sites:
  e9b5ffaf-2fae-43e5-8160-4a0bc36dadd0:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-GB
    name: 'Craft Boilerplate'
    primary: '1'
    siteGroup: 13a10389-f66f-49d3-bbfe-5a5918ca298f
    sortOrder: '1'
system:
  edition: solo
  live: true
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
volumes:
  2704582f-5c82-44da-9552-cddd0a262a82:
    fieldLayouts:
      fc3c2174-735f-42b1-8ed7-73f02694ab13:
        tabs:
          - fields:
              1daffcc0-78ad-4066-934f-57421e0bd5ef:
                required: false
                sortOrder: 1
              2d81e303-5711-4abe-bad0-d7bb9cb25068:
                required: false
                sortOrder: 3
              52e82fa9-0507-4677-9f2b-f34dbc5aeddb:
                required: false
                sortOrder: 2
            name: Content
            sortOrder: 1
    handle: images
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/uploads/images'
    sortOrder: null
    type: craft\volumes\Local
    url: '@assetUrl/uploads/images'
