contentColumnType: text
fieldGroup: f8b7bde8-597c-4a27-b7f2-3fec26edff9b
handle: instagramUsername
instructions: 'Instagram Username. Usually the part after _www.instgram.com/_. Click on the ''Settings'' tab on your Instagram company/fan page and find your ''Username''.'
name: 'Instagram Username'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: 4
  multiline: ''
  placeholder: username
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
