contentColumnType: string(32)
fieldGroup: cc080ac8-3f30-49ef-8e41-29cb76818d16
handle: postCode
instructions: ''
name: 'Post Code'
searchable: true
settings:
  byteLimit: null
  charLimit: 8
  code: ''
  columnType: null
  initialRows: 4
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
