contentColumnType: text
fieldGroup: fa1be04a-5fe4-4dad-a59c-7d52eee2b403
handle: teaserBody
instructions: "The teaser copy, sometimes referred to as the excerpt,  is used for article/page summaries. \r\nThis is typically used in listing pages and related link modules.  "
name: 'Teaser Body'
searchable: true
settings:
  byteLimit: null
  charLimit: 120
  code: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: ''
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
