contentColumnType: text
fieldGroup: cc080ac8-3f30-49ef-8e41-29cb76818d16
handle: telephone
instructions: ''
name: Telephone
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: 4
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
