contentColumnType: text
fieldGroup: f8b7bde8-597c-4a27-b7f2-3fec26edff9b
handle: twitterHandle
instructions: 'Twitter username for the website - without the preceding @. '
name: 'Twitter Handle'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: 4
  multiline: ''
  placeholder: handle
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
