contentColumnType: text
fieldGroup: f8b7bde8-597c-4a27-b7f2-3fec26edff9b
handle: youtubeUrl
instructions: 'The URL for your YouTube channel, account or playlist. To find your YouTube url or to create one please read this [YouTube help article](https://support.google.com/youtube/answer/2657968?hl=en-GB)'
name: 'YouTube URL'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: 4
  multiline: ''
  placeholder: handle
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
