enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  0f11f7ce-ae36-4dee-9ecd-d1cf1167181a:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
